#!/bin/bash

#SBATCH --job-name=convert_files
#SBATCH --account=def-itobias
#SBATCH --time'=02:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --error=%x_%j_error.txt
#SBATCH --output=%x_%j_output.txt

# we must convert gziped files to bgzip files for ArchR
module load samtools/1.22.1
module load htslib/1.22.1

#dowload data
wget https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5393630
wget https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5393631
wget https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5393632

#gunzip files
gunzip *.tsv.gz

mkdir fragment_files 
mv *.tsv.gz fragment_files/

cd fragment files

echo $PWD
echo *

#bgzips the file, the -f flag overwrites the older file
bgzip -f *.tsv

#check for whether it actually got bgzipped by checking the file type
echo htsfile *.tsv
